info:
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
server:
  port: 8080
management:
  port: 8080
  address: 127.0.0.1
  context-path: /manage
validator:
  context-path: /validator
spring:
  jackson:
    serialization-inclusion: non_null
  datasource:
    url: jdbc:h2:file:~/ticketdb;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    generate-ddl: true
    properties.javax.persistence:
      sharedCache.mode: NONE
    hibernate:
      ddl-auto: create-drop
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      scope: read, write
      authorized_grant_types: authorization_code, refresh_token, password
      accessTokenValiditySeconds: 1800
      auto-approve-scopes: '.*'
endpoints:
  shutdown:
    sensitive: false
    enabled: true
  jolokia:
    sensitive: true
    enabled: true
swagger:
  api:
    info:
      title: "Spring-validator DEMO API"
      description: "Validate REST requests"
      termsOfServiceUrl: "https://github.com/create1st/spring-validation"
      contact: "Sebastian Gil"
      license: "Apache License Version 2.0"
      licenseUrl: "https://github.com/create1st/spring-validation/blob/master/LICENSE"
      version: "2.0"